### ISSUE TITLE
Add back dropdown of parents

### ISSUE THREAD

**Issue by drazisil** [drazisil/parent-folder#2]

**Comment by bdcomp** [comment]
Hi,

I am missing this feature.
Any chance to get it back any time soon?

Thanks!

**Comment by drazisil** [comment]
@bdcomp Now that I know people use that feature I'll see what I can do to get it back :)

**Comment by bdcomp** [comment]
Thanks, waiting to the next version...

**Comment by drazisil** [comment]
@bdcomp It can be found at https://addons.mozilla.org/en-US/firefox/addon/parent-folder/versions/?page=1#version-4.5.6 until it's reviewed
